FROM node:12-alpine3.11
RUN mkdir -p /var/www/dockerize-nuxt/nuxt-app
WORKDIR /var/www/dockerize-nuxt/nuxt-app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 2500

ENV NUXT_HOST=0.0.0.0

ENV NUXT_PORT=2500

CMD [ "npm", "start" ]